export { default as icon01 } from './auto_stories.png'
export { default as icon02 } from './desktop_mac.png'
export { default as icon03 } from './school.png'
export { default as icon04 } from './card_travel.png'
export { default as icon05 } from './clock (1) 1.png'
export { default as icon06 } from './check-mark 1.png'
export { default as icon07 } from './workout 1.png'
export { default as icon08 } from './dawn 1.png'
export { default as icon09 } from './clap 1.png'
export { default as icon10 } from './music-notes 1.png'
